services:
  - type: web
    name: emowolf-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: CORS_ORIGIN
        value: https://emowolf.vercel.app
